//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyrsovaya_2_etap_formi
{
    using System;
    using System.Collections.Generic;
    
    public partial class estimate
    {
        public int code_est { get; set; }
        public string name_est { get; set; }
        public int code_shedule { get; set; }
    
        public virtual shedule shedule { get; set; }
    }
}
