//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyrsovaya_2_etap_formi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolEntitiesTrue : DbContext
    {
        public SchoolEntitiesTrue()
            : base("name=SchoolEntitiesTrue")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<estimate> estimate { get; set; }
        public virtual DbSet<lectors> lectors { get; set; }
        public virtual DbSet<parents> parents { get; set; }
        public virtual DbSet<salary> salary { get; set; }
        public virtual DbSet<shedule> shedule { get; set; }
        public virtual DbSet<students> students { get; set; }
        public virtual DbSet<subjects> subjects { get; set; }
    }
}
