//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyrsovaya_2_etap_formi
{
    using System;
    using System.Collections.Generic;
    
    public partial class lectors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lectors()
        {
            this.salary = new HashSet<salary>();
            this.shedule = new HashSet<shedule>();
        }
    
        public int code_lector { get; set; }
        public string surname_lector { get; set; }
        public string name_lector { get; set; }
        public string lastname_lector { get; set; }
        public System.DateTime birthday_lector { get; set; }
        public string post { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<salary> salary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shedule> shedule { get; set; }
    }
}
