//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyrsovaya_2_etap_formi
{
    using System;
    using System.Collections.Generic;
    
    public partial class salary
    {
        public int code_salary { get; set; }
        public int code_lector { get; set; }
        public Nullable<int> work_hour { get; set; }
        public Nullable<int> experience { get; set; }
        public string mounth { get; set; }
        public int summ { get; set; }
    
        public virtual lectors lectors { get; set; }
    }
}
