//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyrsovaya_2_etap_formi
{
    using System;
    using System.Collections.Generic;
    
    public partial class shedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public shedule()
        {
            this.estimate = new HashSet<estimate>();
        }
    
        public int code_shedule { get; set; }
        public int code_stud { get; set; }
        public int code_subject { get; set; }
        public int code_lector { get; set; }
        public System.DateTime date_classes { get; set; }
        public string time_classes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estimate> estimate { get; set; }
        public virtual lectors lectors { get; set; }
        public virtual students students { get; set; }
        public virtual subjects subjects { get; set; }
    }
}
